export const enUS = {
  site: { title: "Create Next App", description: "Generated by create next app" },
  errors: {
    "Name is required": "Name is required",
    "Password is required": "Password is required",
    "Email is required": "Email is required",
    "Invalid email": "Invalid email",
    "Must have at least {{min}} characters": "Must have at least {{min}} characters",
  },
};
