export const ptBR = {
  site: { title: "Create Next App", description: "Generated by create next app" },
  errors: {
    "Name is required": "Nome é obrigatório",
    "Password is required": "Senha é obrigatório",
    "Email is required": "E-mail é obrigatório",
    "Invalid email": "E-mail inválido",
    "Must have at least {{min}} characters": "Deve ter pelo menos {{min}} caracteres",
  },
};
